/**
 * AgriChain — PDF Generation Utilities
 * Creates styled PDF certificates and batch journey reports.
 */
import jsPDF from "jspdf";

/**
 * Generates and downloads a Quality Certificate PDF.
 */
export function downloadCertificatePDF({ batchId, produceType, farmLocation, grade, passed, remarks, issuedAt, inspectorAddress }) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, M = 20;

  // Header background
  doc.setFillColor(26, 107, 58);
  doc.rect(0, 0, W, 55, "F");

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("🌾 AgriChain", M, 22);

  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Blockchain Agricultural Supply Chain", M, 32);

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("QUALITY CERTIFICATE", M, 47);

  // Certificate body
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  let y = 70;

  // Grade badge box
  const gradeColor = passed ? [6, 95, 70] : [153, 27, 27];
  const gradeBg    = passed ? [209, 250, 229] : [254, 226, 226];
  doc.setFillColor(...gradeBg);
  doc.roundedRect(M, y, W - 2 * M, 22, 4, 4, "F");
  doc.setTextColor(...gradeColor);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(`Grade ${grade} — ${passed ? "PASSED ✓" : "REJECTED ✗"}`, W / 2, y + 14, { align: "center" });

  y += 32;

  // Details table
  const fields = [
    ["Batch ID",      `#${batchId}`],
    ["Produce Type",  produceType],
    ["Farm Location", farmLocation],
    ["Issue Date",    issuedAt],
    ["Inspector",     inspectorAddress ? inspectorAddress.slice(0, 20) + "..." : "—"],
    ["Remarks",       remarks || "No remarks"],
  ];

  doc.setTextColor(107, 114, 128);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  fields.forEach(([label, value], i) => {
    const rowY = y + i * 16;
    if (i % 2 === 0) {
      doc.setFillColor(249, 250, 248);
      doc.rect(M, rowY - 5, W - 2 * M, 14, "F");
    }
    doc.setTextColor(107, 114, 128);
    doc.setFontSize(8);
    doc.text(label.toUpperCase(), M + 4, rowY + 2);
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(String(value), M + 4, rowY + 9);
    doc.setFont("helvetica", "normal");
  });

  y += fields.length * 16 + 20;

  // Blockchain verification note
  doc.setFillColor(232, 245, 238);
  doc.roundedRect(M, y, W - 2 * M, 20, 3, 3, "F");
  doc.setTextColor(26, 107, 58);
  doc.setFontSize(9);
  doc.text("⬡  This certificate is immutably recorded on the Ethereum Sepolia blockchain.", M + 6, y + 9);
  doc.text("    Verify authenticity at any time using the batch ID above.", M + 6, y + 16);

  // Footer
  doc.setFillColor(249, 250, 248);
  doc.rect(0, 275, W, 22, "F");
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(8);
  doc.text("Generated by AgriChain — Blockchain Agricultural Supply Chain Platform", W / 2, 283, { align: "center" });
  doc.text(`Generated on: ${new Date().toLocaleString()}`, W / 2, 289, { align: "center" });

  doc.save(`AgriChain_Certificate_Batch_${batchId}.pdf`);
}

/**
 * Generates and downloads a Batch Journey PDF.
 */
export function downloadJourneyPDF({ batchId, produceType, farmLocation, harvestDate, quantity, certification, status, history, cert }) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, M = 20;

  // Header
  doc.setFillColor(26, 107, 58);
  doc.rect(0, 0, W, 50, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("🌾 AgriChain", M, 20);
  doc.setFontSize(13);
  doc.setFont("helvetica", "normal");
  doc.text("Complete Batch Journey Report", M, 30);
  doc.setFontSize(11);
  doc.text(`Batch #${batchId} — ${produceType}`, M, 42);

  let y = 62;

  // Batch info
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("BATCH INFORMATION", M, y);
  y += 6;
  doc.setLineWidth(0.5);
  doc.setDrawColor(26, 107, 58);
  doc.line(M, y, W - M, y);
  y += 8;

  const batchFields = [
    ["Produce",      produceType],
    ["Quantity",     `${quantity} kg`],
    ["Farm Location", farmLocation],
    ["Certification", certification],
    ["Harvest Date",  harvestDate],
    ["Status",        status],
  ];

  doc.setFontSize(9);
  batchFields.forEach(([k, v], i) => {
    const col = i % 2 === 0 ? M : W / 2;
    const row = y + Math.floor(i / 2) * 12;
    doc.setTextColor(107, 114, 128);
    doc.setFont("helvetica", "normal");
    doc.text(k.toUpperCase(), col, row);
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(String(v), col, row + 6);
    doc.setFontSize(9);
  });

  y += Math.ceil(batchFields.length / 2) * 12 + 16;

  // Journey timeline
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text("SUPPLY CHAIN JOURNEY", M, y);
  y += 6;
  doc.setDrawColor(26, 107, 58);
  doc.line(M, y, W - M, y);
  y += 10;

  const steps = [
    { icon: "🌾", title: `Harvested — ${farmLocation}`, meta: `${harvestDate} · Registered on blockchain` },
    ...history.map((h, i) => ({
      icon:  i === 0 ? "🚛" : i === 1 ? "🏪" : "📦",
      title: `${h.notes} — ${h.location}`,
      meta:  `${h.timestamp} · ${h.transport} · Temp: ${h.temp}°C`,
    })),
  ];

  steps.forEach((step, i) => {
    doc.setFillColor(232, 245, 238);
    doc.roundedRect(M, y, W - 2 * M, 16, 2, 2, "F");
    doc.setTextColor(26, 107, 58);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(`${i + 1}. ${step.title}`, M + 4, y + 7);
    doc.setTextColor(107, 114, 128);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(step.meta, M + 4, y + 13);
    y += 20;
    if (y > 260) { doc.addPage(); y = 20; }
  });

  // Quality cert if available
  if (cert) {
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text("QUALITY CERTIFICATE", M, y);
    y += 8;
    doc.setFillColor(cert.passed ? [209, 250, 229] : [254, 226, 226]);
    doc.roundedRect(M, y, W - 2 * M, 20, 3, 3, "F");
    doc.setTextColor(cert.passed ? 6 : 153, cert.passed ? 95 : 27, cert.passed ? 70 : 27);
    doc.setFontSize(13);
    doc.text(`Grade ${cert.grade} — ${cert.passed ? "PASSED" : "REJECTED"}`, W / 2, y + 9, { align: "center" });
    doc.setFontSize(9);
    doc.text(`Issued: ${cert.issuedAt}`, W / 2, y + 16, { align: "center" });
  }

  doc.save(`AgriChain_Journey_Batch_${batchId}.pdf`);
}
